### ISSUE TITLE
Remove https://pkiraly.github.io/qa-catalogue-web/

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue-web#202]
The gh-pages branch is outdated and is not maintained. We should aim for one single source of documentation and possibly generate multiple output from there.

**Comment by pkiraly** [comment]
I removed the URL, now i returns 404 error. I disabled the building of the branch. I did not emptied however the branch. 

What would be your suggestion for the documentation? Do you have a good example in mind? 

We maintain READMEs, however right now the backend README is quite complex. We also have some wiki pages, but only because to not add those text to README. So if we decide a new tarteg for the documentation, these could be the sources.

**Comment by nichtich** [comment]
An option would be to create a handbook for all of qa-catalogue, written with [quarto](https://quarto.org/), and reduce each README to one page, linking to the handbook. But this is work and time is limited!

**Comment by pkiraly** [comment]
quarto sounds good. What do you think about the practicalities: would it require to create a new repository (e.g.  `qa-catalogue-handbook`), or should we use a branch of existing repo (e.g. `qa-catalogue`)?

**Comment by nichtich** [comment]
It should better be a new repository because it should cover multiple source code repositories. The book can bue build and published via GitHub Action as we do [here](https://github.com/nfdi4objects/n4o-graph/blob/main/.github/workflows/quarto-publish.yml) - I could create a boilerplate but only after vacation in three weeks.
